import Instructions from '@/components/NewModals/Instructions';
import { getImage, getVideo } from '@/utils/imagekit';
import React, { useState } from 'react';

const footerAssets = {
  downloadApp: '/images/footer/downloadApk.webp',
  gcLogo: '/images/footer/gc.webp',
  sponsors: [
    '/images/footer/sponsor1.webp',
    '/images/footer/sponsor2.webp',
    '/images/footer/sponsor3.webp',
    '/images/footer/sponsor4.webp',
    '/images/footer/sponsor5.webp',
    '/images/footer/sponsor6.webp',
    '/images/footer/sponsor7.webp',
    '/images/footer/sponsor8.webp',
    '/images/footer/sponsor9.webp',
    '/images/footer/sponsor10.webp',
  ],
  socialMedia: [
    {
      img: '/images/footer/s1.webp',
      path: 'https://www.whatsapp.com',
    },
    {
      img: '/images/footer/s2.webp',
      path: 'https://www.youtube.com',
    },
    {
      img: '/images/footer/s3.webp',
      path: 'https://www.telegram.com',
    },
    {
      img: '/images/footer/s4.webp',
      path: 'https://www.instagram.com',
    },
    {
      img: '/images/footer/s5.webp',
      path: 'https://www.facebook.com',
    },
  ],
};

const footerLinks = [
  { id: 1, label: 'How to Login' },
  { id: 2, label: 'Introduction' },
  { id: 3, label: 'How to Withdraw' },
  { id: 4, label: 'How to Deposit English' },
  { id: 5, label: 'How to Deposit Hindi' },
];

export default function Footer() {
  const [openModalType, setOpenModalType] = useState(null);
  return (
    <>
      <footer className="bg-black text-white py-10 ">
        {/* Download App */}
        <div className="border-b-[1px] border-[#282828] text-center   xl:container mx-auto xl:px-0 px-2 md:px-4 ">
          <div className="flex justify-center mb-6">
            <img
              src={getImage(footerAssets.downloadApp)}
              alt="Download App"
              className="h-12"
            />
          </div>

          {/* Links */}
          <div className="grid grid-cols-2 justify-self-center md:flex md:flex-wrap md:justify-center gap-2 md:gap-4 mb-8">
            {footerLinks.map((link, index) => (
              <button
                key={link.id}
                onClick={() => setOpenModalType(link.id)}
                className={`bg-primary-1300 whitespace-nowrap md:px-4 py-2 rounded-md text-14 ${
                  index === footerLinks.length - 1
                    ? 'col-span-2 justify-self-center'
                    : ''
                }`}
              >
                {link.id}. {link.label}
              </button>
            ))}
          </div>

          {/* GC Logo + Description */}
          <div className="flex flex-col md:flex-row items-center gap-4 mb-8">
            <img
              src={getImage(footerAssets.gcLogo)}
              alt="GC Gaming Curacao"
              className="mx-auto h-12 mb-4"
            />
            <p className="text-white text-[13px] leading-4 font-medium">
              LOTUS365 is a limited liability company incorporated under the
              laws of Curacao. Players are requested not to contact any
              untrusted sources for LOTUS365 accounts as this is an online site
              and they can only register independently without any agents. Only
              deposit through the account details generated by the system or
              provided by our official support team.
            </p>
          </div>

          {/* Sponsors */}
          <div className="flex flex-wrap justify-center gap-6 mb-8">
            {footerAssets.sponsors.map((src, i) => (
              <img
                key={i}
                src={getImage(src)}
                alt={`Sponsor ${i + 1}`}
                className="h-[27px] w-20"
              />
            ))}
          </div>
        </div>
        <div className="xl:container mx-auto xl:px-0 px-4">
          {/* Social Media */}
          <div className="flex justify-center gap-3 mt-4 mb-6">
            {footerAssets.socialMedia.map((src, i) => (
              <img
                onClick={() => window.open(src.path, '_blank')}
                key={i}
                src={getImage(src.img)}
                alt={`Social Media ${i + 1}`}
                className="h-9 w-9 rounded-full overflow-hidden cursor-pointer hover:scale-110 transition"
              />
            ))}
          </div>

          {/* Copyright */}
          <div className="text-gray-400 text-14 text-center">
            Rules Regulations 2016-2025 v. 9.66
          </div>
        </div>
      </footer>

      {openModalType && (
        <Instructions
          isOpen={!!openModalType}
          handleClose={() => setOpenModalType(null)}
          text={
            openModalType === 1
              ? 'How to Login'
              : openModalType === 2
              ? 'Introduction'
              : openModalType === 3
              ? 'How to Withdraw'
              : openModalType === 4
              ? 'How to Deposit English'
              : 'How to Deposit Hindi'
          }
          videoFile={
            openModalType === 1
              ? getVideo('/videos/first.mp4', { q: 75 })
              : openModalType === 2
              ? getVideo('/videos/second.mp4', { q: 75 })
              : openModalType === 3
              ? getVideo('/videos/third.mp4', { q: 75 })
              : openModalType === 4
              ? getVideo('/videos/fourth.mp4', { q: 75 })
              : getVideo('/videos/five.mp4', { q: 75 })
          }
        />
      )}
    </>
  );
}
