// UI Action
export const SET_UI = 'SET_UI';
export const INIT = 'INIT';
export const CLEANUP = 'CLEANUP';
export const SET_USER = 'SET_USER';
export const REFRESH_USER_DETAILS = 'REFRESH_USER_DETAILS';

// actions/betConstants.js
export const SET_SELECTED_BET = 'SET_SELECTED_BET';
export const CURRENT_CALCULATION = 'CURRENT_CALCULATION';
export const USER_EVENT_BETS = 'USER_EVENT_BETS';
export const FETCH_BET_DETAILS = 'FETCH_BET_DETAILS';
export const FETCH_CURRENT_CALCULATION = 'FETCH_CURRENT_CALCULATION';
export const FETCH_USER_EVENT_BETS = 'FETCH_USER_EVENT_BETS';
export const SET_BET_PLACEMENT_SUCCESS = 'SET_BET_PLACEMENT_SUCCESS';
